name: ESLint

on:
  pull_request:

env:
  NODE_VERSION: 12

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: lint lib
        run: |
          cd lib
          npm ci
          npm run lint

      - name: test app
        run: |
          cd app
          cat package.json
          npm ci
          npm run lint
