name: JS test

on:
  pull_request:

env:
  NODE_VERSION: 12

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: test lib
        run: |
          cd lib
          npm ci
          npm run test
          npm run build

      - name: test app
        run: |
          cd app
          npm i @c4dt/libcrowdnotifier@file:../lib
          npm run test
