# This workflow will run tests using node and then publish a package to npm when a release is created

name: Publish npm Package

on:
  push:
    tags:
      - "v*"

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: cd lib && npm ci
      - run: cd lib && npm test
  
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: cd lib && npm ci
      - run: cd lib && npm test

  publish-npm-lib:
    needs: build-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd lib && npm ci
      - run: cd lib && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-npm-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd app && npm ci
      - run: cd app && npm publish
        env:
          NODE_AUTH_TOKEN: ${{SECRETS.NPM_TOKEN}}
